### ISSUE TITLE
Why quotes are added to the Strings by default ? 

### ISSUE THREAD

**Issue by ValentinOzanne** [worldline/3loc#5]
Hi Damien,
I think this behavior is not very convenient and user-friendly. 
Do you have a specific reason to implement it ?
Thanks

**Comment by feugy** [comment]
This matter has been discussed in internal chat room, but I quote here for historical purpose:

Here is an example of a template scenario:

``` javascript
const expect = require(`chai`).expect;

return () => request({
    method: `<$ method $>` || `GET`,
    url: `<$ host $><$ url $>`,
    followRedirect: false
  }).then(expectStatusCode(<$ code $>))
```

All placeholders needs to be quoted when they are used in a context of a string (properties `method` and `url`, but not if the context is a boolean, array, object or number (status code expectation for example).

By using ["type-awarness"](https://github.com/worldline/3loc#templating) and automatically adding quotes when placeholder value is a string, we can simplify this template to:

``` javascript
const expect = require(`chai`).expect;

return () => request({
    method: <$ method $> || `GET`,
    url: <$ host $> + <$ url $>,
    followRedirect: false
  }).then(expectStatusCode(<$ code $>))
```

The downsize is that in that example, we need to use a concatenation between host and url placeholder.
